# Generated by Django 4.2.5 on 2023-09-30 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100, verbose_name='cname')),
                ('cost_per_hr', models.IntegerField(verbose_name='cost_per_hr')),
                ('seats', models.IntegerField(verbose_name='seats')),
                ('fule_type', models.CharField(max_length=100, verbose_name='fule_type')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('stocks', models.IntegerField(verbose_name='stocks')),
            ],
        ),
        migrations.CreateModel(
            name='credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='uname')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=100, verbose_name='passwd')),
            ],
        ),
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='place')),
            ],
        ),
        migrations.CreateModel(
            name='rental_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.IntegerField(verbose_name='tcost')),
                ('start_date', models.DateField(verbose_name='sdate')),
                ('end_date', models.DateField(verbose_name='edate')),
                ('pick_place', models.CharField(max_length=100, verbose_name='pplace')),
                ('drop_place', models.CharField(max_length=100, verbose_name='dplace')),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental_app.car_detail')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental_app.credentials')),
            ],
        ),
        migrations.CreateModel(
            name='rental_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.IntegerField(verbose_name='tcost')),
                ('start_date', models.DateField(verbose_name='sdate')),
                ('end_date', models.DateField(verbose_name='edate')),
                ('pick_place', models.CharField(max_length=100, verbose_name='pplace')),
                ('drop_place', models.CharField(max_length=100, verbose_name='dplace')),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental_app.car_detail')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental_app.credentials')),
            ],
        ),
    ]
